Repository Surcharges/Back-end, pull requests merged in 2025-02, with the labels that each got.

#60 Added two more statuses to backend enums #27
  functions/src/data/surcharge/get/DTO/GetSurchargesRepositoryResponse.ts
  functions/src/data/surcharge/put/DTO/PutSurchargeRepositoryRequest.ts
  functions/src/domain/place/get/place/entity/GetPlaceUsecaseResponse.ts
  functions/src/domain/surcharge/get/entity/GetSurchargeUsecaseResponse.ts
  functions/src/domain/surcharge/put/entity/SurchargeStatus.ts
  functions/src/shared/types/surcharge/SurchargeStatus.ts
Labels: enhancement

#59 rateCalculatorHelper updated #58
  functions/src/domain/surcharge/helpers/rateCalculatorHelper.ts
  functions/src/domain/surcharge/put/putSurchargeUsecase.ts
Labels: bug

#62 GetFranchiseRepository created and used into GetSurchargesRepository
  functions/src/data/franchise/get/franchise/GetFranchiseRepository.ts
  functions/src/data/franchise/index.ts
  functions/src/data/surcharge/get/getSurchargesRepository.ts
  functions/src/domain/place/get/place/getPlaceUsecase.ts
  functions/src/domain/place/get/places/GetPlacesUsecase.ts
Labels: enhancement

#63 If there is not any result, server will return 404 error. #23
  functions/src/data/place/get/places/GetPlacesRepository.ts
  functions/src/domain/place/get/places/GetPlacesUsecase.ts
  functions/src/interface/place/get/places/getPlacesInterface.ts
Labels: bug

#64 Release
  .github/workflows/build-validator.yml
  functions/src/data/firebase/Firebase.ts
  functions/src/data/firebase/index.ts
  functions/src/data/franchise/get/franchise/GetFranchiseRepository.ts
  functions/src/data/franchise/index.ts
  functions/src/data/image/get/image/DTO/ImageDTO.ts
  functions/src/data/image/get/image/GetImageRepository.ts
  functions/src/data/image/index.ts
  functions/src/data/place/get/place/DTO/PlaceDTO.ts
  functions/src/data/place/get/places/DTO/GetPlacesRepositoryRequest.ts
  functions/src/data/place/get/places/DTO/GetPlacesRepositoryResponse.ts
  functions/src/data/place/get/places/GetPlacesRepository.ts
  functions/src/data/place/index.ts
  functions/src/data/place/post/place/DTO/PostPlaceRepositoryRequest.ts
  functions/src/data/surcharge/get/DTO/GetSurchargesRepositoryResponse.ts
  functions/src/data/surcharge/get/getSurchargesRepository.ts
  functions/src/data/surcharge/index.ts
  functions/src/data/surcharge/put/DTO/PutSurchargeRepositoryRequest.ts
  functions/src/data/surcharge/put/PutSurchargeRepository.ts
  functions/src/domain/image/get/image/entity/GetImageUsecaseRequest.ts
  functions/src/domain/image/get/image/entity/GetImageUsecaseResponse.ts
  functions/src/domain/image/get/image/getImageUsecase.ts
  functions/src/domain/image/index.ts
  functions/src/domain/place/get/place/entity/GetPlaceUsecaseResponse.ts
  functions/src/domain/place/get/place/getPlaceUsecase.ts
  functions/src/domain/place/get/places/GetPlacesUsecase.ts
  functions/src/domain/place/get/places/getPlacesUsecase.ts
  functions/src/domain/place/index.ts
  functions/src/domain/surcharge/get/entity/GetSurchargeUsecaseResponse.ts
  functions/src/domain/surcharge/get/getSurchargeUsecase.ts
  functions/src/domain/surcharge/get/getSurchargesUsecase.ts
  functions/src/domain/surcharge/helpers/rateCalculatorHelper.ts
  functions/src/domain/surcharge/index.ts
  functions/src/domain/surcharge/post/RateCalculator.ts
  functions/src/domain/surcharge/put/entity/PutSurchargeUsecaseRequest.ts
  functions/src/domain/surcharge/put/entity/SurchargeStatus.ts
  functions/src/domain/surcharge/put/putSurchargeUsecase.ts
  functions/src/index.ts
  functions/src/interface/image/get/image/getImageInterface.ts
  functions/src/interface/image/get/image/model/GetImageInterfaceResponse.ts
  functions/src/interface/image/index.ts
  functions/src/interface/place/get/places/getPlacesInterface.ts
  functions/src/interface/place/get/places/getPlacesWithSurchargesInterface.ts
  functions/src/interface/place/index.ts
  functions/src/interface/surcharge/get/getSurchargesInterface.ts
  functions/src/interface/surcharge/index.ts
  functions/src/interface/surcharge/put/models/PutSurchargeInterfaceRequest.ts
  functions/src/interface/surcharge/put/putSurchargeInterface.ts
  functions/src/shared/authentication/AdminAuth.ts
  functions/src/shared/constants/LocationRestrictions.ts
  functions/src/shared/constants/index.ts
  functions/src/shared/types/place/Place.ts
  functions/src/shared/types/surcharge/SurchargeStatus.ts
Labels: release
